import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'concepts next14',
  description: 'Generated by create next app',
};

export default function ConceptsNext14Layout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="bg-blue-950 text-white">
      <nav>oi</nav> {children}
    </section>
  );
}
