import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ActiveLink } from './components/active-link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <aside className="fixed left-0 flex h-screen w-50 flex-col bg-green-300 pt-20 text-gray-50 shadow-lg">
          <ActiveLink href="/">Home</ActiveLink>
          <ActiveLink href="/users">Users</ActiveLink>
          <ActiveLink href="/solid">Solid Estudo</ActiveLink>
        </aside>
        <div className="bg-blue-950 h-screen text-white">{children}</div>
      </body>
    </html>
  );
}
